name: Build with Code Coverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  neth-tests:
    name: Nethermind Tests
    env:
      EXCLUDE_TEST_PROJECTS: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*%2c[Nethermind.DataMarketplace.Test]*%2c[Ethereum.Test.Base]*"'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #  os: [ubuntu-latest, windows-latest, macOS]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow --progress --prune origin +refs/heads/*:refs/remotes/origin/*
    - name: Updating submodules
      run: git submodule update --init src/Dirichlet src/rocksdb-sharp
    - name: Installing Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Installing macOS packages
      if: matrix.os == 'macOS'
      run: brew install gmp && brew install snappy && brew install lz4 && brew install zstd
    - name: Tests
      run: |
        dotnet test -c Release $EXCLUDE_TEST_PROJECTS src/Nethermind/Nethermind.sln
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        name: codecov-nethermind 
  eth-tests:
    name: Ethereum Tests
    env:
      EXCLUDE_TEST_PROJECTS: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*%2c[Nethermind.DataMarketplace.Test]*%2c[Ethereum.Test.Base]*"'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
      #  os: [ubuntu-latest, windows-latest, macOS]
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Updating submodules
      run: git -c submodule."src/eth2.0-spec-tests".update=none submodule update --init
    - name: Tests
      run: |
        dotnet test -c Release $EXCLUDE_TEST_PROJECTS src/Nethermind/EthereumTests.sln
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        name: codecov-nethermind
#  eth2-tests:
#    name: Ethereum 2.0 Tests
#    env:
#      EXCLUDE_TEST_PROJECTS: '/p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[Nethermind.HashLib]*%2c[Nethermind.Core.Test]*%2c[Nethermind.Blockchain.Test]*%2c[Nethermind.DataMarketplace.Test]*%2c[Ethereum.Test.Base]*"'
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#      #  os: [ubuntu-latest, windows-latest, macOS]
#        os: [ubuntu-latest]
#    steps:
#    - uses: actions/checkout@v2-beta
#      with:
#        lfs: true
#    - name: Updating submodules
#      run: git -c submodule."src/tests".update=none submodule update --init
#    - name: Ethereum.Bls.Test
#      run: |
#        dotnet test -c Release $EXCLUDE_TEST_PROJECTS src/Nethermind/Ethereum2.Bls.Test
#    - name: Ethereum.Ssz.Test
#      run: |
#        dotnet test -c Release $EXCLUDE_TEST_PROJECTS src/Nethermind/Ethereum2.Ssz.Test
#    - name: Upload coverage reports to Codecov
#      uses: codecov/codecov-action@v1.0.3
#      with:
#        token: ${{secrets.CODECOV_TOKEN}}
#        name: codecov-nethermind
