name: Standard Build

on: push

jobs:
  neth-tests:
    name: Nethermind Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow --progress --prune origin +refs/heads/*:refs/remotes/origin/*
    - name: Updating submodules
      run: git -c submodule."src/eth2.0-spec-tests".update=none submodule update --init
    - name: Installing Linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libsnappy-dev libc6-dev libc6
    - name: Installing macOS packages
      if: matrix.os == 'macOS'
      run: brew install gmp && brew install snappy && brew install lz4 && brew install zstd
    - name: Tests
      run: |
        dotnet test -c Release src/Nethermind/Nethermind.sln
  eth-tests:
    name: Ethereum Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS]
    steps:
    - uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Updating submodules
      run: git -c submodule."src/eth2.0-spec-tests".update=none submodule update --init
    - name: Tests
      run: |
        dotnet test -c Release src/Nethermind/EthereumTests.sln
#  eth2-tests:
#    name: Ethereum 2.0 Tests
#    runs-on: ${{ matrix.os }}
#    strategy:
#      matrix:
#        os: [ubuntu-latest, windows-latest, macOS]
#    steps:
#    - uses: actions/checkout@v2-beta
#      with:
#        lfs: true
#    - name: Updating submodules
#      run: git -c submodule."src/tests".update=none submodule update --init
#    - name: Ethereum.Bls.Test
#      run: |
#        dotnet test -c Release src/Nethermind/Ethereum2.Bls.Test
#    - name: Ethereum.Ssz.Test
#      run: |
#        dotnet test -c Release src/Nethermind/Ethereum2.Ssz.Test
