name: Truffle smoke test

on:
  push:
    tags:
    - '*'
  workflow_dispatch:

jobs:
  truffle-tests:
    name: Nethermind truffle tests on Spaceneth
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Unshallow fetching
      run: git fetch --unshallow
    - name: Cloning truffle tests
      run: |
        git clone https://github.com/NethermindEth/truffleTest.git
    - name: Set up docker buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v3.1.0
      with:
        version: latest
    - name: Docker Login
      if: success()
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - name: Build docker image
      run: |
        docker buildx build --platform=linux/amd64 -t neth .
    - name: Setup the Node.js
      uses: actions/setup-node@v1.4.4
      with:
        node-version: '13'
    - run: npm install -g truffle
    - name: Running truffle deploy
      run: |
        docker run --name nethermind --network host -itd neth --config spaceneth_persistent
        cd truffleTest/
        npm i sha3 --save
        npm i
        echo "silly funny task remove diamond maximum rack awesome sting chalk recycle also social banner verify" > .secret
        sleep 20
        truffle deploy --network development
